language: node_js
node_js:
  - "0.10"
python:
  - "2.7"
servies:
  - rabbitmq
  - mongodb
before_script:
  - "npm i -g jasmine-node"
  - "npm i -g jasmine-jquery"
  - "npm i -g brunch"
  - "sudo apt-get update"
  - "sudo apt-get install libevent-dev"
  - "sudo apt-get install -y --yes python-dev python-setuptools python-pip libzmq-dev nodejs npm build-essential python-gevent libevent-dev supervisor ipython-notebook swig libvpx-dev subversion python-pastescript ipython python-opencv python-scipy python-numpy python-pygame libsdl1.2-dev libsmpeg-dev libv4l-dev libfreetype6-dev libpng-dev rabbitmq-server"
  - "sudo pip install gevent"
  - "sudo pip install path.py"
  - "sudo pip install python-dateutil"
  - "sudo pip install pyyaml"
  - "sudo pip install mongoengine"
  - "sudo apt-get install python-pygame"
  - "sudo pip install PIL"
  - "sudo apt-get install python-opencv"
  - "sudo pip install jsonpickle"
  - "sudo pip install https://github.com/sightmachine/SimpleCV/zipball/develop"
  - "sudo pip install flask"
  - "sudo pip install pytz"
  - "sudo pip install amqplib"
  - "sudo pip install gevent-socketio==0.3.5-beta"
script:
  - "sudo python ./SimpleSeer/setup.py develop"
  - "cd SimpleSeer; sudo scripts/setup.sh -i; cd .."
  - "sudo simpleseer deploy"
  - "simpleseer build"
