language: node_js
node_js:
  - "0.10"
python:
  - "2.7"
servies:
  - rabbitmq
  - mongodb
before_script:
  - "npm i -g jasmine-node"
  - "npm i -g jasmine-jquery"
  - "npm i -g brunch"
  - "sudo apt-get update"
  - "sudo apt-get install libevent-dev"
  - "sudo apt-get install supervisor"
  - "sudo apt-get install python-dev"
  - "sudo apt-get install python-setuptools"
  - "sudo apt-get install python-pip"
  - "sudo apt-get install nodejs"
  - "sudo apt-get install npm"
  - "sudo apt-get install build-essential"
  - "sudo apt-get install python-gevent"
  - "sudo apt-get install libevent-dev"
  - "sudo apt-get install supervisor"
  - "sudo apt-get install swig"
  - "sudo apt-get install libvpx-dev"
  - "sudo apt-get install subversion"
  - "sudo apt-get install python-pastescript"
  - "sudo apt-get install ipython"
  - "sudo apt-get install python-opencv"
  - "sudo apt-get install python-scipy"
  - "sudo apt-get install python-numpy"
  - "sudo apt-get install python-pygame"
  - "sudo apt-get install libamd2.2.0"
  - "sudo apt-get install libblas3gf"
  - "sudo apt-get install libc6"
  - "sudo apt-get install libgcc1"
  - "sudo apt-get install libgfortran3"
  - "sudo apt-get install liblapack3gf"
  - "sudo apt-get install libumfpack5.4.0"
  - "sudo apt-get install libstdc++6"
  - "sudo apt-get install build-essential"
  - "sudo apt-get install gfortran"
  - "sudo apt-get install python-all-dev"
  - "sudo apt-get install libsdl1.2-dev"
  - "sudo apt-get install libsmpeg-dev"
  - "sudo pip install gevent"
  - "sudo pip install path.py"
  - "sudo pip install python-dateutil"
  - "sudo pip install pyyaml"
  - "sudo pip install mongoengine"
  - "sudo apt-get install python-pygame"
  - "sudo pip install PIL"
  - "sudo apt-get install python-opencv"
  - "sudo pip install jsonpickle"
  - "sudo pip install https://github.com/sightmachine/SimpleCV/zipball/develop"
  - "sudo pip install flask"
  - "sudo pip install pytz"
  - "sudo pip install amqplib"
  - "sudo pip install gevent-socketio==0.3.5-beta"
script:
  - "sudo python ./SimpleSeer/setup.py develop"
  - "cd SimpleSeer; sudo scripts/setup.sh -i; cd .."
  - "sudo simpleseer deploy"
  - "sudo mongod --config /etc/mongodb.conf"
  - "simpleseer build"
  - "simpleseer web"
  - "simpleseer olap"
