language: node_js
node_js:
  - "0.10"
python:
  - "2.7"
servies:
  - rabbitmq
  - mongodb
before_script:
  - "npm i -g jasmine-node"
  - "npm i -g jasmine-jquery"
  - "pip install gevent"
script:
  - "sudo python ./SimpleSeer/setup.py develop"
  - "cd SimpleSeer; source scripts/setup.sh -i; cd .."
  - "simpleseer deploy"
  - "simpleseer build"
