language: node_js
node_js:
  - "0.10"
python:
  - "2.7"
servies:
  - rabbitmq
  - mongodb
before_script:
  - "npm i -g jasmine-node"
  - "npm i -g jasmine-jquery"
script: "python ./SimpleSeer/setup.py develop"
