language: node_js
node_js:
  - "0.10"
python:
  - "2.7"
servies:
  - rabbitmq
  - mongodb
before_script:
  - "npm i -g jasmine-node"
  - "npm i -g jasmine-jquery"
  - "sudo apt-get install libevent-dev"
  - "sudo pip install gevent"
  - "sudo pip install path.py"
  - "sudo pip install python-dateutil"
  - "sudo pip install pyyaml"
  - "sudo pip install mongoengine"
  - "sudo apt-get install python-pygame"
script:
  - "sudo python ./SimpleSeer/setup.py develop"
  - "cd SimpleSeer; source scripts/setup.sh -i; cd .."
  - "simpleseer deploy"
  - "simpleseer build"
